spring:
  datasource:
    username: postgres
  jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

server:
  port: 5000

telegrambot:
  userName: '@Sergo4Bot'

pingtask:
  url: https://www.google.com
  period: 1200000
